### ISSUE TITLE
ansible-cmdbを実行するとエラーが発生する

### ISSUE THREAD

**Issue by 223n** [223n/lde#4]
## 前提条件

* 各バージョンは、次のとおり。
* ansible-cmdbは、公式Releasesから.debファイルを入手してインストールを行った。

```shell
$ python --version
Python 3.11.2
$ ansible --version
ansible [core 2.14.16]
  config file = /home/ja223n/dev/ansible-local/tasks/ansible.cfg
  configured module search path = ['/home/ja223n/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/ja223n/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Sep 14 2024, 03:00:30) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
$ ansible-cmdb --version
ansible-cmdb.py v1.31
```

## やったこと

* 次のようにoutフォルダを生成後、ansibleから情報を出力、ansible-cmdbに渡したところ、エラーが発生した。
* 生成された ```overview.html``` は、0バイトファイルであった。

```shell
$ mkdir out
$ ansible -m setup --tree out/ localhost
$ ansible-cmdb out/ >overview.html
Traceback (most recent call last):
  File "_usr_lib_ansible_cmdb_ansiblecmdb_data_tpl_html_fancy_tpl", line 18, in _mako_get_namespace
KeyError: ('_usr_lib_ansible_cmdb_ansiblecmdb_data_tpl_html_fancy_tpl', 'defs')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/ansible-cmdb/mako/lookup.py", line 237, in get_template
    return self._check(uri, self._collection[uri])
                            ~~~~~~~~~~~~~~~~^^^^^
KeyError: '/html_fancy_defs.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/../lib/ansible-cmdb/ansible-cmdb.py", line 214, in <module>
    output = renderer.render(ansible.get_hosts(), params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/ansible-cmdb/ansiblecmdb/render.py", line 42, in render
    return self._render_mako(hosts, vars)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/ansible-cmdb/ansiblecmdb/render.py", line 59, in _render_mako
    return template.render(hosts=hosts, **vars)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/ansible-cmdb/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/ansible-cmdb/mako/runtime.py", line 802, in _render
    _render_context(template, callable_, context, *args,
  File "/usr/lib/ansible-cmdb/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/ansible-cmdb/mako/runtime.py", line 860, in _exec_template
    callable_(context, *args, **kwargs)
  File "_usr_lib_ansible_cmdb_ansiblecmdb_data_tpl_html_fancy_tpl", line 31, in render_body
  File "_usr_lib_ansible_cmdb_ansiblecmdb_data_tpl_html_fancy_tpl", line 20, in _mako_get_namespace
  File "_usr_lib_ansible_cmdb_ansiblecmdb_data_tpl_html_fancy_tpl", line 23, in _mako_generate_namespaces
  File "/usr/lib/ansible-cmdb/mako/runtime.py", line 545, in __init__
    self.template = _lookup_template(context, templateuri,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/ansible-cmdb/mako/runtime.py", line 769, in _lookup_template
    return lookup.get_template(uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/ansible-cmdb/mako/lookup.py", line 245, in get_template
    return self._load(srcfile, uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/ansible-cmdb/mako/lookup.py", line 306, in _load
    self._collection[uri] = template = Template(
                                       ^^^^^^^^^
  File "/usr/lib/ansible-cmdb/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/ansible-cmdb/mako/template.py", line 396, in _compile_from_file
    code, module = _compile_text(
                   ^^^^^^^^^^^^^^
  File "/usr/lib/ansible-cmdb/mako/template.py", line 672, in _compile_text
    code = compile(source, cid, 'exec')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_html_fancy_defs_html", line 97
    def render_var_cols(context,cols_visible=,cols_exclude=):
                                            ^
SyntaxError: expected default value expression

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/../lib/ansible-cmdb/ansible-cmdb.py", line 221, in <module>
    full_err = exceptions.text_error_template().render().replace("\n", "\n    ")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/ansible-cmdb/mako/exceptions.py", line 219, in text_error_template
    return mako.template.Template(r"""
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/ansible-cmdb/mako/template.py", line 303, in __init__
    (code, module) = _compile_text(self, text, filename)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/ansible-cmdb/mako/template.py", line 672, in _compile_text
    code = compile(source, cid, 'exec')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "memory:0x7fd651a63150", line 18
    def render_body(context,error=,traceback=,**pageargs):
                                 ^
SyntaxError: expected default value expression
```

## 生成状況（抜粋）

```shell
$ tree
.
├── out
│   └── localhost
└── overview.html
```

**Comment by 223n** [comment]
回避策として、pipxでインストールする方法を試すも、エラーで解決せず。
そもそも、ansible-cmdbの更新が途絶えており、他の手段を探すほうが良さそう；；
